version: '3.5'
services:
  backend_metgroup:
      build:
        context: .
        dockerfile: Dockerfile
      image: docker.pkg.github.com/daka22/metgroup-backend/backend_metgroup:latest
      container_name: backend_metgroup
      restart: always
      networks:
          - network_privated
          - proxy
      depends_on:
          - postgres_metgroup
  postgres_metgroup:
      image: 'postgres:12.9'
      container_name: postgres_metgroup
      restart: always
      environment:
          POSTGRES_DB: 'metgroup'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'admin'
          POSTGRES_HOST_AUTH_METHOD: 'md5'
      volumes:
          - 'postgres_metgroup_db:/var/lib/postgresql/data'
      networks:
          - network_privated
networks:
    network_privated:
        driver: bridge
    proxy:
        driver: bridge
        name: proxy
        external: true

volumes:
  postgres_metgroup_db:
